export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'

export const UPDATE_BASKET_ITEMS = 'UPDATE_BASKET_ITEMS'
export const INCREASE_BASKET_ITEM_COUNT = 'INCREASE_BASKET_ITEM_COUNT'

export const UPDATE_BASKET_MODAL_STATE = 'UPDATE_BASKET_MODAL_STATE'